// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataMeta struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Key                  []byte   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Ring                 int32    `protobuf:"varint,6,opt,name=ring,proto3" json:"ring,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMeta) Reset()         { *m = DataMeta{} }
func (m *DataMeta) String() string { return proto.CompactTextString(m) }
func (*DataMeta) ProtoMessage()    {}
func (*DataMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *DataMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMeta.Unmarshal(m, b)
}
func (m *DataMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMeta.Marshal(b, m, deterministic)
}
func (m *DataMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMeta.Merge(m, src)
}
func (m *DataMeta) XXX_Size() int {
	return xxx_messageInfo_DataMeta.Size(m)
}
func (m *DataMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DataMeta proto.InternalMessageInfo

func (m *DataMeta) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataMeta) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DataMeta) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DataMeta) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DataMeta) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataMeta) GetRing() int32 {
	if m != nil {
		return m.Ring
	}
	return 0
}

type DataContent struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataContent) Reset()         { *m = DataContent{} }
func (m *DataContent) String() string { return proto.CompactTextString(m) }
func (*DataContent) ProtoMessage()    {}
func (*DataContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *DataContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataContent.Unmarshal(m, b)
}
func (m *DataContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataContent.Marshal(b, m, deterministic)
}
func (m *DataContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataContent.Merge(m, src)
}
func (m *DataContent) XXX_Size() int {
	return xxx_messageInfo_DataContent.Size(m)
}
func (m *DataContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DataContent.DiscardUnknown(m)
}

var xxx_messageInfo_DataContent proto.InternalMessageInfo

func (m *DataContent) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *DataContent) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type DataBody struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ring                 int32    `protobuf:"varint,2,opt,name=ring,proto3" json:"ring,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                string   `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	PartitionId          int32    `protobuf:"varint,5,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	PartitionIndex       int32    `protobuf:"varint,6,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	Version              int32    `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	Content              []byte   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataBody) Reset()         { *m = DataBody{} }
func (m *DataBody) String() string { return proto.CompactTextString(m) }
func (*DataBody) ProtoMessage()    {}
func (*DataBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *DataBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataBody.Unmarshal(m, b)
}
func (m *DataBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataBody.Marshal(b, m, deterministic)
}
func (m *DataBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataBody.Merge(m, src)
}
func (m *DataBody) XXX_Size() int {
	return xxx_messageInfo_DataBody.Size(m)
}
func (m *DataBody) XXX_DiscardUnknown() {
	xxx_messageInfo_DataBody.DiscardUnknown(m)
}

var xxx_messageInfo_DataBody proto.InternalMessageInfo

func (m *DataBody) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *DataBody) GetRing() int32 {
	if m != nil {
		return m.Ring
	}
	return 0
}

func (m *DataBody) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DataBody) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DataBody) GetPartitionId() int32 {
	if m != nil {
		return m.PartitionId
	}
	return 0
}

func (m *DataBody) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *DataBody) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DataBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*DataMeta)(nil), "model.DataMeta")
	proto.RegisterType((*DataContent)(nil), "model.DataContent")
	proto.RegisterType((*DataBody)(nil), "model.DataBody")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0xe5, 0xb4, 0x6e, 0xd3, 0x2b, 0xaa, 0x90, 0xc5, 0xe0, 0x81, 0x21, 0xca, 0x80, 0x32,
	0xb1, 0xf0, 0x04, 0xfc, 0x59, 0x18, 0x58, 0xfc, 0x06, 0xd7, 0xde, 0x09, 0x59, 0xa4, 0x76, 0x94,
	0x9e, 0x10, 0x7d, 0x09, 0x9e, 0x91, 0x47, 0x41, 0x71, 0x13, 0x92, 0x32, 0x76, 0xbb, 0xdf, 0x5d,
	0x94, 0xfb, 0xbe, 0x33, 0x00, 0xa1, 0xe0, 0x7d, 0xd3, 0x46, 0x89, 0x46, 0xef, 0x23, 0x71, 0x5d,
	0x7e, 0x2b, 0xc8, 0x5f, 0x50, 0xf0, 0x8d, 0x05, 0x8d, 0x85, 0xe5, 0x27, 0xb7, 0x07, 0x1f, 0x83,
	0x55, 0x85, 0xaa, 0xb4, 0x1b, 0xa2, 0xd9, 0x40, 0xe6, 0xc9, 0x66, 0x85, 0xaa, 0xae, 0x5c, 0xe6,
	0xc9, 0xdc, 0xc2, 0x2a, 0xe0, 0x9e, 0x0f, 0x0d, 0xee, 0xd8, 0xce, 0x0a, 0x55, 0xad, 0xdc, 0xd8,
	0x30, 0x37, 0xa0, 0x05, 0xb7, 0x35, 0xdb, 0x79, 0x9a, 0x9c, 0x82, 0xb9, 0x86, 0xd9, 0x07, 0x1f,
	0xad, 0x4e, 0x3f, 0xe9, 0x4a, 0x63, 0x60, 0xde, 0xfa, 0xf0, 0x6e, 0x17, 0x69, 0x59, 0xaa, 0xcb,
	0x47, 0x58, 0x77, 0x3c, 0xcf, 0x31, 0x08, 0x07, 0xe9, 0x90, 0x88, 0x6b, 0x16, 0xa6, 0x84, 0x94,
	0xbb, 0x21, 0x76, 0x93, 0xdd, 0xe9, 0xa3, 0x9e, 0x6b, 0x88, 0xe5, 0x4f, 0xef, 0xf4, 0x14, 0xe9,
	0xd8, 0x93, 0xab, 0x3f, 0xf2, 0x61, 0x67, 0x36, 0xee, 0xbc, 0xc8, 0xa6, 0x80, 0x75, 0x83, 0xad,
	0x78, 0xf1, 0x31, 0xbc, 0x52, 0xb2, 0xd2, 0x6e, 0xda, 0x32, 0x77, 0xb0, 0x19, 0x63, 0x20, 0xfe,
	0xea, 0x3d, 0xff, 0x75, 0xa7, 0x57, 0x5f, 0x9e, 0x5f, 0x7d, 0xa2, 0x98, 0x9f, 0x29, 0x6e, 0x17,
	0xe9, 0x11, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x52, 0x81, 0x3b, 0x60, 0xd2, 0x01, 0x00,
	0x00,
}
