// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Description struct {
	Namespace            int32    `protobuf:"varint,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table                int32    `protobuf:"varint,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Description) Reset()         { *m = Description{} }
func (m *Description) String() string { return proto.CompactTextString(m) }
func (*Description) ProtoMessage()    {}
func (*Description) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *Description) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Description.Unmarshal(m, b)
}
func (m *Description) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Description.Marshal(b, m, deterministic)
}
func (m *Description) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Description.Merge(m, src)
}
func (m *Description) XXX_Size() int {
	return xxx_messageInfo_Description.Size(m)
}
func (m *Description) XXX_DiscardUnknown() {
	xxx_messageInfo_Description.DiscardUnknown(m)
}

var xxx_messageInfo_Description proto.InternalMessageInfo

func (m *Description) GetNamespace() int32 {
	if m != nil {
		return m.Namespace
	}
	return 0
}

func (m *Description) GetTable() int32 {
	if m != nil {
		return m.Table
	}
	return 0
}

type Repository struct {
	DataCenter           int32    `protobuf:"varint,1,opt,name=DataCenter,proto3" json:"DataCenter,omitempty"`
	Area                 int32    `protobuf:"varint,2,opt,name=Area,proto3" json:"Area,omitempty"`
	Rack                 int32    `protobuf:"varint,3,opt,name=Rack,proto3" json:"Rack,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetDataCenter() int32 {
	if m != nil {
		return m.DataCenter
	}
	return 0
}

func (m *Repository) GetArea() int32 {
	if m != nil {
		return m.Area
	}
	return 0
}

func (m *Repository) GetRack() int32 {
	if m != nil {
		return m.Rack
	}
	return 0
}

type Partition struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Partition) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Partition) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type Storage struct {
	Partitions           []*Partition `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Storage) Reset()         { *m = Storage{} }
func (m *Storage) String() string { return proto.CompactTextString(m) }
func (*Storage) ProtoMessage()    {}
func (*Storage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *Storage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storage.Unmarshal(m, b)
}
func (m *Storage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storage.Marshal(b, m, deterministic)
}
func (m *Storage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storage.Merge(m, src)
}
func (m *Storage) XXX_Size() int {
	return xxx_messageInfo_Storage.Size(m)
}
func (m *Storage) XXX_DiscardUnknown() {
	xxx_messageInfo_Storage.DiscardUnknown(m)
}

var xxx_messageInfo_Storage proto.InternalMessageInfo

func (m *Storage) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Namespace struct {
	Desc                 *Description `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Id                   int32        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetDesc() *Description {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *Namespace) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Table struct {
	Desc                 *Description `protobuf:"bytes,1,opt,name=desc,proto3" json:"desc,omitempty"`
	Id                   int32        `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetDesc() *Description {
	if m != nil {
		return m.Desc
	}
	return nil
}

func (m *Table) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Description)(nil), "model.Description")
	proto.RegisterType((*Repository)(nil), "model.Repository")
	proto.RegisterType((*Partition)(nil), "model.Partition")
	proto.RegisterType((*Storage)(nil), "model.Storage")
	proto.RegisterType((*Namespace)(nil), "model.Namespace")
	proto.RegisterType((*Table)(nil), "model.Table")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xc1, 0x4b, 0x33, 0x31,
	0x10, 0xc5, 0xd9, 0xed, 0xee, 0x57, 0x76, 0x96, 0x4f, 0x64, 0xf0, 0xb0, 0x07, 0x91, 0x92, 0x83,
	0xf4, 0xb4, 0x48, 0x3d, 0x7a, 0x2a, 0xf6, 0x26, 0x88, 0xa4, 0x05, 0xcf, 0xe9, 0x66, 0x90, 0x60,
	0x9b, 0x84, 0x24, 0x88, 0xfe, 0xf7, 0x92, 0x6c, 0x5a, 0x17, 0xbc, 0x7a, 0x9b, 0xf7, 0x66, 0xf7,
	0x97, 0x97, 0x17, 0xf8, 0xef, 0x83, 0x71, 0xe2, 0x8d, 0x7a, 0xeb, 0x4c, 0x30, 0x58, 0x1f, 0x8d,
	0xa4, 0x03, 0x5b, 0x43, 0xbb, 0x21, 0x3f, 0x38, 0x65, 0x83, 0x32, 0x1a, 0xaf, 0xa1, 0xd1, 0xe2,
	0x48, 0xde, 0x8a, 0x81, 0xba, 0x62, 0x51, 0x2c, 0x6b, 0xfe, 0x63, 0xe0, 0x15, 0xd4, 0x41, 0xec,
	0x0f, 0xd4, 0x95, 0x69, 0x33, 0x0a, 0xb6, 0x03, 0xe0, 0x64, 0x8d, 0x57, 0xc1, 0xb8, 0x2f, 0xbc,
	0x01, 0xd8, 0x88, 0x20, 0x1e, 0x49, 0x07, 0x72, 0x19, 0x31, 0x71, 0x10, 0xa1, 0x5a, 0x3b, 0x12,
	0x19, 0x91, 0xe6, 0xe8, 0x71, 0x31, 0xbc, 0x77, 0xb3, 0xd1, 0x8b, 0x33, 0x7b, 0x82, 0xe6, 0x45,
	0xb8, 0xa0, 0x52, 0xac, 0x0e, 0xe6, 0x1f, 0xe4, 0xbc, 0x32, 0x3a, 0x13, 0x4f, 0x12, 0x2f, 0xa0,
	0x54, 0x32, 0xc3, 0x4a, 0x25, 0x63, 0x44, 0xa5, 0x25, 0x7d, 0x66, 0xd6, 0x28, 0xd8, 0x03, 0xcc,
	0xb7, 0xe3, 0xed, 0xf1, 0x0e, 0xc0, 0x9e, 0xb8, 0xbe, 0x2b, 0x16, 0xb3, 0x65, 0xbb, 0xba, 0xec,
	0x53, 0x19, 0xfd, 0xf9, 0x40, 0x3e, 0xf9, 0x86, 0xbd, 0x42, 0xf3, 0x7c, 0xae, 0xe0, 0x16, 0x2a,
	0x49, 0x7e, 0x48, 0x31, 0xda, 0x15, 0xe6, 0x1f, 0x27, 0x15, 0xf2, 0xb4, 0xff, 0x95, 0x0b, 0xa1,
	0x8a, 0x3d, 0xa6, 0x58, 0x0d, 0x4f, 0x33, 0xdb, 0x42, 0xbd, 0x8b, 0x0d, 0xfe, 0x25, 0x74, 0xff,
	0x2f, 0x3d, 0xef, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x97, 0x72, 0x13, 0xef, 0x01,
	0x00, 0x00,
}
